# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cameron McKay
email: me@cdmckay.org
description: >- # this means to ignore newlines until "baseurl:"
  I'm Cameron McKay: a computer programmer and traveller.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cdmckay.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username: cdmckay
mastodon:
  - instance: mastodon.social
    username: cdmckay
twitter_username: cdmckay
show_excerpts: true
excerpt_separator: <!--more-->
permalink: /:title
paginate: 10

algolia:
  application_id: "8SWIT7VNGI"
  index_name: "posts"
  nodes_to_index: "p,blockquote,li,pre"

# Google Analytics
google_analytics: UA-7505226-3

# Disqus for comments
disqus:
  shortname: cdmckay

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

safe: true
whitelist:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

# Minima settings
header_pages:
  - search/index.html
  - about/index.md
  - projects/index.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .idea/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
